Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
reversed_arr = np.flip(arr)
print(reversed_arr)

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

In [4]:
flattened_array1 = array1.flatten()
print(flattened_array1)

[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[1, 2], [3, 4]])


In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [6]:
comparison = np.array_equal(arr1, arr2)
print(comparison)

True


(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [7]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

In [8]:
from scipy import stats

In [10]:
mode_x = stats.mode(x)
most_frequent_value_x = mode_x.mode
indices_x = np.where(x == most_frequent_value_x)

In [11]:
print("Most frequent value in x:", most_frequent_value_x)
print("Indices in x:", indices_x)

Most frequent value in x: 1
Indices in x: (array([0, 5, 7, 8, 9]),)


In [12]:
mode_y = stats.mode(y)
most_frequent_value_y = mode_y.mode
indices_y = np.where(y == most_frequent_value_y)

In [14]:
print("Most frequent value in y:", most_frequent_value_y)
print("Indices in y:", indices_y)

Most frequent value in y: 1
Indices in y: (array([0, 1, 2]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [15]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [16]:
total_sum = np.sum(gfg)
print("Total sum:", total_sum)

Total sum: 45


In [17]:
row_sum = np.sum(gfg, axis=1)
print("Row-wise sum:", row_sum)

Row-wise sum: [[14]
 [16]
 [15]]


In [18]:
col_sum = np.sum(gfg, axis=0)
print("Column-wise sum:", col_sum)

Column-wise sum: [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii.Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [19]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

In [20]:
sum_diag = np.trace(n_array)
print("Sum of diagonal elements:", sum_diag)

Sum of diagonal elements: 176


In [21]:
eigen_values, eigen_vectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigen_values)
print("Eigenvectors:\n", eigen_vectors)

Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [22]:
inverse_matrix = np.linalg.inv(n_array)
print("Inverse of matrix:\n", inverse_matrix)

Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [23]:
det_matrix = np.linalg.det(n_array)
print("Determinant of matrix:", det_matrix)

Determinant of matrix: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]   q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]  q = [[4, 5, 1], [6, 7, 2]]

In [24]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

In [25]:
product_pq = np.dot(p, q)
print("Product of p and q:\n", product_pq)

Product of p and q:
 [[16 19]
 [26 31]]


In [26]:
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

In [27]:
product_p2q2 = np.dot(p2, q2)
print("Product of p2 and q2:\n", product_p2q2)

Product of p2 and q2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [28]:
cov_pq = np.cov(p, q)
print("Covariance between matrices:\n", cov_pq)

Covariance between matrices:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [29]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

In [30]:
inner_product = np.inner(x, y)
print("Inner product:\n", inner_product)

Inner product:
 [[17 52]
 [13 62]]


In [31]:
outer_product = np.outer(x, y)
print("Outer product:\n", outer_product)

Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [32]:
cartesian_product = np.array(np.meshgrid(x, y)).T.reshape(-1, 2)
print("Cartesian product:\n", cartesian_product)

Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics

(a)For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [33]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

In [34]:
abs_array = np.abs(array)
print("Element-wise absolute value:\n", abs_array)

Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]


In [35]:
percentiles_flattened = np.percentile(array, [25, 50, 75])
print("Percentiles for the flattened array:", percentiles_flattened)

Percentiles for the flattened array: [-3.5 -0.5  2.5]


In [36]:
percentiles_col = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles for each column:\n", percentiles_col)

Percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


In [37]:
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles for each row:\n", percentiles_row)

Percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [38]:
mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_flattened = np.std(array)

In [39]:
print("Mean (flattened):", mean_flattened)

Mean (flattened): -0.5


In [40]:
print("Median (flattened):", median_flattened)

Median (flattened): -0.5


In [41]:
print("Standard Deviation (flattened):", std_flattened)

Standard Deviation (flattened): 3.8622100754188224


In [44]:
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

In [45]:
print("Mean for each column:", mean_col)

Mean for each column: [-1.5  1.5 -1.5]


In [46]:
print("Median for each column:", median_col)

Median for each column: [-1.5  1.5 -1.5]


In [47]:
print("Standard Deviation for each column:", std_col)

Standard Deviation for each column: [2.5 3.5 4.5]


In [48]:
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

In [49]:
print("Mean for each row:", mean_row)

Mean for each row: [ 0.66666667 -1.66666667]


In [50]:
print("Median for each row:", median_row)

Median for each row: [ 1. -4.]


In [51]:
print("Standard Deviation for each row:", std_row)

Standard Deviation for each row: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [52]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

In [53]:
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)

In [54]:
print("Floor values:", floor_values)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]


In [55]:
print("Ceiling values:", ceiling_values)

Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]


In [56]:
print("Truncated values:", truncated_values)

Truncated values: [-1. -1. -0.  0.  1.  1.  3.]


In [57]:
rounded_values = np.round(a)
print("Rounded values:", rounded_values)

Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find i. Sorted array
ii. Indices of sorted array iii. 4 smallest elements iv. 5 largest elements

In [58]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

In [59]:
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

Sorted array: [ 10  16  16  52  54  62 453]


In [60]:
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

Indices of sorted array: [0 3 4 1 5 2 6]


In [61]:
smallest_elements = np.sort(array)[:4]
print("4 smallest elements:", smallest_elements)

4 smallest elements: [10 16 16 52]


In [62]:
largest_elements = np.sort(array)[-5:]
print("5 largest elements:", largest_elements)

5 largest elements: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find i. Integer elements only
ii. Float elements only

In [63]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [64]:
integer_elements = array[array == array.astype(int)]
print("Integer elements only:", integer_elements)

Integer elements only: [1. 2. 3. 2.]


In [65]:
float_elements = array[array != array.astype(int)]
print("Float elements only:", float_elements)

Float elements only: [1.2 2.2]


Q4:

(a) Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)

In [66]:
from PIL import Image
import numpy as np

In [67]:
def img_to_array(path):
    img = Image.open(path)
    if img.mode == 'RGB':
        img_array = np.array(img)
        np.savetxt('image_rgb.txt', img_array.reshape(-1, 3), fmt='%d')
    elif img.mode == 'L':
        img_array = np.array(img)
        np.savetxt('image_greyscale.txt', img_array, fmt='%d')

In [68]:
img_to_array('/content/elisabeth-arnold-oPmIQeKYeqc-unsplash.jpg')

(b) Load the saved file into jupyter notebook?

In [75]:
import numpy as np

In [69]:
image_rgb = np.loadtxt('image_rgb.txt').reshape(-1, 3)

In [73]:
print("Loaded RGB image array:\n", image_rgb)

Loaded RGB image array:
 [[  2. 136. 199.]
 [  2. 136. 199.]
 [  3. 137. 200.]
 ...
 [ 26.  26.  26.]
 [ 26.  26.  26.]
 [ 27.  27.  27.]]


In [78]:
image = Image.open('/jonas-aberg-DmgwxkcdFCM-unsplash.jpg')
image_greyscale = np.array(image)

In [79]:
print("Loaded Greyscale image array:\n", image_greyscale)

Loaded Greyscale image array:
 [[[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [238 238 238]
  [239 239 239]
  [239 239 239]]

 [[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [239 239 239]
  [239 239 239]
  [239 239 239]]

 [[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [239 239 239]
  [239 239 239]
  [240 240 240]]

 ...

 [[ 41  41  41]
  [ 45  45  45]
  [ 32  32  32]
  ...
  [215 215 215]
  [217 217 217]
  [219 219 219]]

 [[ 52  52  52]
  [ 38  38  38]
  [ 42  42  42]
  ...
  [216 216 216]
  [217 217 217]
  [217 217 217]]

 [[ 65  65  65]
  [ 42  42  42]
  [ 51  51  51]
  ...
  [218 218 218]
  [218 218 218]
  [217 217 217]]]
